### ISSUE TITLE
gcc vs g++ issue on OSX

### ISSUE THREAD

**Issue by silentrob** [EducationalTestingService/python-zpar#16]
Not sure if anyone will see this, but I had issues compiling with GCC 4.9 on OSX 10.9.5 (Mavericks) 
You need to make sure to use g++ and NOT gcc as they call a different standard lib.

This is not really an issue per-say just a gotcha.

**Comment by desilinguist** [comment]
Rob,

Thanks for the post. The README does say a C++ compiler but I will further
clarify. :)
