### ISSUE TITLE
Logging setup

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/python-zpar#18]
Currently, we modifying the config for the root logger in `Tagger.py` etc. using `logging.basicConfig`. This is not a good idea. 

Actually, it looks like we aren't really using logging there in any meaningful way, so may be we can just get rid of logging from those files altogether?

**Comment by enavarro222** [comment]
:+1: 

At least you could just remove from the lib all the:
```python
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.WARNING)
```

It activates default logging handler that you may not want in an app importing `zpar`. This should be done only in main fct (as it is done in examples).

**Comment by desilinguist** [comment]
@enavarro222 you are right. That's why I wanted to change things in the first place. I will do a new release as soon as I get a chance :+1:

**Comment by desilinguist** [comment]
Sorry for the delayed. This is now addressed and merged in `master`.
