### ISSUE TITLE
adding lemmas? 

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/python-zpar#19]
Would it be possible to also get lemma information from the dependency parser?

**Comment by desilinguist** [comment]
I am going to use the WordNet lemmatizer for this (via `nltk`) but I am going to make it optional. If ask for lemmas and you have `nltk` installed, you will get them otherwise you will get a warning and no lemmas.

**Comment by desilinguist** [comment]
Addressed by #22.
