### ISSUE TITLE
Universal Dependencies and Stanford Dependencies

### ISSUE THREAD

**Issue by xushenkun** [EducationalTestingService/python-zpar#24]
How can I change the default depparser using universal dependencies or Stanford dependencies?
The default tagsets is "ROOT AMOD DEP NMOD OBJ P PMOD PRD SBAR SUB VC VMOD". I can't find any description for them anymore and can't use them in my project.

**Comment by desilinguist** [comment]
I think this issue belongs in ZPar since this is just a wrapper.

**Comment by xushenkun** [comment]
Thanks. Can I use the generic version of depparser to train a model using corpus with other types of dependency? And where can I get an English corpus to train a new model? The DEP/CON models in v0.7.5 are not updated anymore.

**Comment by desilinguist** [comment]
Have you read the section in the manual: http://people.sutd.edu.sg/~yue_zhang/doc/doc/deppar.html ?
