### ISSUE TITLE
Installing on MAC OS X

### ISSUE THREAD

**Issue by atishsawant** [EducationalTestingService/python-zpar#28]
I’m using MAC OSX and the command:

 

CXX=/usr/bin/gcc  make –e    

 

Doesn’t work when I’m in the unzipped directory? It seems like it fails on the wget command for the underlying zpar from github. Actual output: 

make: wget: No such file or directory

**Actually just solved this part. 

Still results in this error eventually though: 

error: call to function 'operator>>' that is
      neither visible in the template definition nor found by argument-dependent
      lookup

Same one that I get in the individual zpar directory when trying to install it independently.  

So I downloaded the individual zpar, and tried to install that separately but that one leads to errors that I believe are related to clang. Using the same CXX command within that file also didn’t work.

**Comment by desilinguist** [comment]
Are you sure you have wget installed and in your path?

**Comment by atishsawant** [comment]
That was my earlier mistake. I fixed that. THe call to function error still persists however.

**Comment by desilinguist** [comment]
Did you read the warning in the README about how `clang` will not work and you need to install `gcc` via either `macports` or `homebrew`?

**Comment by atishsawant** [comment]
Yep, I used the CXX command as noted to point to the gcc compiler instead to run. But that still persisted.

**Comment by desilinguist** [comment]
Can you tell me what `/usr/bin/gcc --version` prints out?

**Comment by atishsawant** [comment]
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

is the result.

**Comment by desilinguist** [comment]
This is why I asked you earlier if you followed the instructions properly.
As the README clearly says, the default macOS compiler (clang) will not
work. Please install gcc via MacPorts or home brew and use that.

**Comment by atishsawant** [comment]
GCC is already installed. I thought by pointing it to /usr/bin/gcc it would fix the problem? 

brew install gcc results in "Warning: gcc 7.3.0 is already installed"

**Comment by atishsawant** [comment]
Solved the problem. On newer MAC OS X's brew installing gcc, doesn't make the gcc in /usr/bin point to the gcc compiler and it will still be clang. Have to go to where brew installed gcc, and pick out a gcc version from there to compile with. 
It still kicked out an error when compiling from the correct file, but in the second run it worked just fine.
