### ISSUE TITLE
install failure on Linux server

### ISSUE THREAD

**Issue by Anker-Lee** [EducationalTestingService/python-zpar#35]
pip install python-zpar
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting python-zpar
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/73/80/6961436556d7720239234a41e564cd30eed632f0f3a39ca8d82f288fb858/python-zpar-0.9.5.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: python-zpar
  Building wheel for python-zpar (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running bdist_wheel
      running build
      running build_zpar
      compiling zpar library
      ********************************************************************************
      error: [Errno 2] No such file or directory: 'make'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-zpar
  Running setup.py clean for python-zpar
Failed to build python-zpar
Installing collected packages: python-zpar
  Running setup.py install for python-zpar ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for python-zpar did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running install
      /opt/conda/envs/rstenv/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_zpar
      compiling zpar library
      ********************************************************************************
      error: [Errno 2] No such file or directory: 'make'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-zpar

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by desilinguist** [comment]
> error: [Errno 2] No such file or directory: 'make

You need to have make installed. Please read the full instructions in the README carefully.

**Comment by Anker-Lee** [comment]
> 

Ok, i will check the readme carefully, thx!
